
import React from 'react';
import {
  ShieldCheck,
  Lock,
  User,
  Users,
  Vote,
  BarChart,
  PlusCircle,
  Settings,
  LayoutDashboard as Dashboard,
  Loader2 as Spinner,
  Mail,
  Link as Blockchain,
  History,
  Download,
  ExternalLink,
  CheckCircle2 as CheckCircle,
  Trash2 as Trash,
  Plus,
  Rocket,
  AlertCircle,
} from 'lucide-react';

export const Icons = {
  shieldCheck: ShieldCheck,
  lock: Lock,
  user: User,
  users: Users,
  vote: Vote,
  barChart: BarChart,
  plusCircle: PlusCircle,
  settings: Settings,
  dashboard: Dashboard,
  spinner: Spinner,
  mail: Mail,
  blockchain: Blockchain,
  history: History,
  download: Download,
  externalLink: ExternalLink,
  checkCircle: CheckCircle,
  trash: Trash,
  plus: Plus,
  rocket: Rocket,
  alertCircle: AlertCircle,
};